project:
  type: website

website:
  title: "personal_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: engineering.qmd
        text: Engineering
      - href: research.qmd
        text: Research

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



