---
title: "Research Work"
---

Working in Dr. Farhad Imani's Integrated Systems and Control Laboratory (ISCL)
at the University of Connecticut, I did research utilizing machine learning to 
better understand the multiphysics of additive manufacturing.

1. ExplainHD: Neuro-Symbolic Computing for Explainable Characterization of
Process-Structure-Property Relationships

Machine learning can accurately predict material properties from machine
characteristics. However, we as humans are incapable of tracing our fingers
through its answers to understand how it came up with them. What this work aims
to do is create a methodology for explainably detailing the importance that
individual features of data have in contributing to correct characterizations of
material samples.

[]

The figure shown above describes the process by which ExplainHD, the
aforementioned methodology, operates to classify part samples. The procedure
starts with hyperdimensional encoding, where data is rewritten to be represented
with -1, 0, and +1.

[DESCRIBE THE 
FIGURE FURTHER HERE]

2. PSPRAG: Utilizing an Efficient Language Model to Access In-Depth Material
Information for Additive Manufacturing

Because of the multiphysics nature of additive manufacturing, much study has
been taken to identify the behavior of a given material within a given process
under given processing conditions. These previous research works have identified
which sets of parameters are productive, but because of the wide variety of
setups and final results, it is difficult to easily identify correct
interpolations and valuable information for additive manufacturing calibration.
To remedy this, I wrote my thesis about my work on PSPRAG, a Retrieval-Augmented
Generation method for generating accurate process-structure-property-related
information for a given 